export type FontFamily =
  | "MontserratBlack"
  | "MontserratBlackItalic"
  | "MontserratBold"
  | "MontserratBoldItalic"
  | "MontserratExtraBold"
  | "MontserratExtraBoldItalic"
  | "MontserratExtraLight"
  | "MontserratExtraLightItalic"
  | "MontserratItalic"
  | "MontserratLight"
  | "MontserratLightItalic"
  | "MontserratMedium"
  | "MontserratMediumItalic"
  | "MontserratRegular"
  | "MontserratSemiBold"
  | "MontserratSemiBoldItalic"
  | "MontserratThin"
  | "MontserratThinItalic"
  | "InterBold"
  | "InterBoldItalic"
  | "InterExtraBold"
  | "InterExtraBoldItalic"
  | "InterItalic"
  | "InterLight"
  | "InterLightItalic"
  | "InterMedium"
  | "InterMediumItalic"
  | "InterRegular"
  | "InterSemiBold"
  | "InterSemiBoldItalic";

export type FontFamilyType = { type: FontFamily };
